# vim: filetype=python

## load our own python modules
import system
from build_tools import find_files_recursive

import os

# import build env
Import('plugin_env')
local_env = plugin_env.Clone()

# Automatically add all source and include files found in the source path
src_base_dir  = os.path.join(local_env['ROOT_DIR'], 'maya', 'alembicHolder')
source_files  = find_files_recursive(src_base_dir, ['.c', '.cpp'])
include_files = find_files_recursive(src_base_dir, ['.h'])

JSON_INCLUDE_PATH = local_env['JSON_INCLUDE_PATH']
JSON_LIB = local_env['JSON_LIB']
BOOST_LIBS = local_env['BOOST_LIBS']

local_env.Append(CPPPATH = local_env['CPPPATH']  + [JSON_INCLUDE_PATH])
local_env.Append(LIBPATH = local_env["LIBPATH"] + [BOOST_LIBS])
local_env.Append(LIBS = local_env["LIBS"] + [JSON_LIB] )


MAYA_VIEWER = local_env.SharedLibrary('alembicHolder', source_files, LIBPREFIX='')

Return('MAYA_VIEWER')
