# vim: filetype=python

## load our own python modules
import system
from build_tools import find_files_recursive

import os

# import build env
Import('mtoa_env')
local_env = mtoa_env.Clone()

# Automatically add all source and include files found in the source path
src_base_dir  = os.path.join(local_env['ROOT_DIR'], 'mtoa', 'ABCViewer')
source_files  = find_files_recursive(src_base_dir, ['.c', '.cpp'])
include_files = find_files_recursive(src_base_dir, ['.h'])

BOOST_INCLUDE_PATH = local_env['BOOST_INCLUDE_PATH']

local_env.Append(CPPPATH = local_env['CPPPATH']  + [BOOST_INCLUDE_PATH])


MTOA_VIEWER = local_env.SharedLibrary('ABCViewer', source_files, LIBPREFIX='')

Return('MTOA_VIEWER')
