find_library(MTOA_API_LIB NAMES mtoa_api PATHS ${MTOA_LIBRARY} NO_DEFAULT_PATH)
set(MTOA_LIBS ${MTOA_API_LIB})

MESSAGE(STATUS "MTOA INCLUDE PATH: ${MTOA_INCLUDE_DIR}" )
MESSAGE(STATUS "MTOA LIBS: ${MTOA_LIBS}" )

