find_library(ALEMBIC_ALEMBIC_LIB NAMES Alembic PATHS ${ALEMBIC_LIBRARY} NO_DEFAULT_PATH)
set (ALEMBIC_LIBS ${ALEMBIC_ALEMBIC_LIB})

MESSAGE(STATUS "ALEMBIC INCLUDE PATH: ${ALEMBIC_INCLUDE_DIR}" )
MESSAGE(STATUS "ALEMBIC LIBS: ${ALEMBIC_LIBS}" )


