find_library(HDF5_HL_LIB NAMES hdf5_hl PATHS ${HDF5_LIBRARY} NO_DEFAULT_PATH)
find_library(HDF5_LIB NAMES hdf5 PATHS ${HDF5_LIBRARY} NO_DEFAULT_PATH)
set(HDF5_LIBS ${HDF5_HL_LIB} ${HDF5_LIB})

MESSAGE(STATUS "HDF5 INCLUDE PATH: ${HDF5_INCLUDE_DIR}" )
MESSAGE(STATUS "HDF5 LIBS: ${HDF5_LIBS}" )

