find_library(JSONCPP_LIB NAMES jsoncpp PATHS ${JSONCPP_LIBRARY} NO_DEFAULT_PATH)
SET( JSONCPP_LIBS ${JSONCPP_LIB} )

MESSAGE(STATUS "JSONCPP INCLUDE PATH: ${JSONCPP_INCLUDE_DIR}" )
MESSAGE(STATUS "JSONCPP LIBRARIES: ${JSONCPP_LIBS}" )
