find_library(ZLIB_LIB NAMES zlib PATHS ${ZLIB_LIBRARY} NO_DEFAULT_PATH)
SET( ALEMBIC_ZLIB_LIBS ${ZLIB_LIB} )

MESSAGE(STATUS "ZLIB INCLUDE PATH: ${ZLIB_INCLUDE_DIR}" )
MESSAGE(STATUS "ZLIB LIBRARIES: ${ALEMBIC_ZLIB_LIBS}" )

