find_library(ILMBASE_IEX_LIB NAMES Iex PATHS ${ILMBASE_LIBRARY} NO_DEFAULT_PATH)
find_library(ILMBASE_HALF_LIB NAMES Half PATHS ${ILMBASE_LIBRARY} NO_DEFAULT_PATH)
find_library(ILMBASE_IMATH_LIB NAMES Imath PATHS ${ILMBASE_LIBRARY} NO_DEFAULT_PATH)
find_library(ILMBASE_ILMTHREAD_LIB NAMES IlmThread PATHS ${ILMBASE_LIBRARY} NO_DEFAULT_PATH)
find_library(ILMBASE_IEXMATH_LIB NAMES IexMath PATHS ${ILMBASE_LIBRARY} NO_DEFAULT_PATH)
SET( ILMBASE_LIBS 
    ${ILMBASE_IEX_LIB}
    ${ILMBASE_HALF_LIB}
    ${ILMBASE_IMATH_LIB}
    ${ILMBASE_ILMTHREAD_LIB}
    ${ILMBASE_IEXMATH_LIB}   
)

MESSAGE(STATUS "ILMBASE INCLUDE PATH: ${ILMBASE_INCLUDE_DIR}" )
MESSAGE(STATUS "ILMBASE LIBS: ${ILMBASE_LIBS}" )
