find_library( MAYA_OPENMAYA_LIB NAME OpenMaya PATHS ${MAYA_LIBRARY} NO_DEFAULT_PATH )
find_library( MAYA_FOUNDATION_LIB NAME Foundation PATHS ${MAYA_LIBRARY} NO_DEFAULT_PATH )
find_library( MAYA_OPENMAYAANIM_LIB NAME OpenMayaAnim PATHS ${MAYA_LIBRARY} NO_DEFAULT_PATH )
find_library( MAYA_OPENMAYAFX_LIB NAME OpenMayaFX PATHS ${MAYA_LIBRARY} NO_DEFAULT_PATH )
find_library( MAYA_OPENMAYAUI_LIB NAME OpenMayaUI PATHS ${MAYA_LIBRARY} NO_DEFAULT_PATH )
find_library( MAYA_OPENMAYARENDER_LIB NAME OpenMayaRender PATHS ${MAYA_LIBRARY} NO_DEFAULT_PATH )
find_library( MAYA_IMAGE_LIB NAME Image PATHS ${MAYA_LIBRARY} NO_DEFAULT_PATH )
set (MAYA_LIBS
    ${MAYA_OPENMAYA_LIB}
    ${MAYA_FOUNDATION_LIB}
    ${MAYA_OPENMAYAANIM_LIB}
    ${MAYA_OPENMAYAFX_LIB} 
    ${MAYA_OPENMAYAUI_LIB}
    ${MAYA_OPENMAYARENDER_LIB}
    ${MAYA_IMAGE_LIB} )

if(DARWIN)
    set(MAYA_PLUGIN_SUFFIX ".bundle")
elseif(WINDOWS)
    set(MAYA_PLUGIN_SUFFIX ".mll")
else() #LINUX
    set(MAYA_PLUGIN_SUFFIX ".so")
endif()

MESSAGE(STATUS "MAYA INCLUDE PATH: ${MAYA_INCLUDE_DIR}" )
MESSAGE(STATUS "MAYA LIBS: ${MAYA_LIBS}" )

