find_library(AI_LIB NAMES ai PATHS ${ARNOLD_LIBRARY} NO_DEFAULT_PATH)
set(ARNOLD_LIBS ${AI_LIB})

MESSAGE(STATUS "ARNOLD INCLUDE PATH: ${ARNOLD_INCLUDE_DIR}" )
MESSAGE(STATUS "ARNOLD LIBS: ${ARNOLD_LIBS}" )

