find_library(PYSTRING_LIB NAMES pystring PATHS ${PYSTRING_LIBRARY} NO_DEFAULT_PATH)
SET( PYSTRING_LIBS ${PYSTRING_LIB} )

MESSAGE(STATUS "PYSTRING INCLUDE PATH: ${PYSTRING_INCLUDE_DIR}" )
MESSAGE(STATUS "PYSTRING LIBRARIES: ${PYSTRING_LIBS}" )
